<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: youngkwon
 * Date: Tue, 06 Aug 2013 15:15:18 -0400
 */

$conf['title'] = 'Methodikos Web Application Project';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
